CREATE TABLE construction(
	kadastr INTEGER PRIMARY KEY UNIQUE NOT NULL,
	address VARCHAR(300) NOT NULL, 
	district VARCHAR(100) NOT NULL, 
	land SMALLINT NOT NULL CHECK(land > 10)
);

CREATE TABLE flat(
	square_hall SMALLINT PRIMARY KEY NOT NULL, 
	branch SMALLINT NOT NULL, 
	hallnum SMALLINT NOT NULL CHECK(hallnum < 110), 
	storey SMALLINT NOT NULL, 
	height SMALLINT NOT NULL, 
	level BOOLEAN NOT NULL,
	rooms SMALLINT NOT NULL
);

CREATE TABLE room(
	square_part SMALLINT PRIMARY KEY NOT NULL,
	record SMALLINT NOT NULL CHECK(record < 10),
	size SMALLINT NOT NULL
);